name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr Export
        run: west zephyr-export
      - name: West Build (Cygnus Left)
        run: west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=cygnus_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Cygnus Left Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-cygnus-left
          path: build/zephyr/zmk.uf2
      - name: West Build (Cygnus Right)
        run: west build -s zmk/app -b nice_nano_v2 --pristine -- -DSHIELD=cygnus_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Cygnus Right Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-cygnus-right
          path: build/zephyr/zmk.uf2 